In [1]:
import os
os.getcwd()

'C:\\Users\\Meena Panday'

In [2]:
#!pip install numpy

In [3]:
#call numpy library
import numpy as np

In [4]:
#to show version of numpy
np.__version__

'1.18.5'

In [5]:
#Create a 1D array with the help of list : -  
L=[34,67,89,32,10]
print("Type of list : ",type(L))

Type of list :  <class 'list'>


In [6]:
#convert List L into 1D numpy array
A=np.array(L) 
#array() inbuilt function of numpy library
print("Type of A : ",type(A))

Type of A :  <class 'numpy.ndarray'>


In [7]:
#check which type of dimension  , use inbuilt method ndim
A.ndim

1

In [8]:
#How many roes and columns in given numpy array A , use inbuilt attributes
#shape
A.shape

(5,)

In [9]:
#To show no. of rows in given numpy array A
A.shape[0]

5

In [10]:
#To find the no. of elements in numpy array A , use inbuilt attributes size
A.size

5

In [11]:
#or len() 
len(A) #python's function

5

In [12]:
#to check the datatype of numpy array A ,use inbuilt attributes : dtype
A.dtype

dtype('int32')

In [13]:
#to check byte occupy by each element of numpy array A , use inbuilt 
#attributes itemsize
A.itemsize

4

In [14]:
#Find total bytes occupied by Numpy Array A
A.itemsize*A.size

20

In [15]:
#direct use : nbytes : inbuilt attributes
A.nbytes

20

In [16]:
'''
Inbuilt Attributes of numpy array :
1. ndim
2. size
3. dtype
4. shape
5. itemsize
6. nbytes
'''

'\nInbuilt Attributes of numpy array :\n1. ndim\n2. size\n3. dtype\n4. shape\n5. itemsize\n6. nbytes\n'

In [17]:
#suppose create 1D array
X=np.array([56,78.9,43,90,32,10])
print(X)
print(X.dtype)

[56.  78.9 43.  90.  32.  10. ]
float64


In [18]:
X=np.array([12,34,True,90,False,67])
print(X)
print(X.dtype)

[12 34  1 90  0 67]
int32


In [19]:
X=np.array([12,34,'True',90,'False',67])
print(X)
print(X.dtype)

['12' '34' 'True' '90' 'False' '67']
<U11


In [20]:
A=np.array([45,78.8,67,89.4,30,20],int)
print(A)
print(A.dtype)

[45 78 67 89 30 20]
int32


In [21]:
#to extract data from numpy array X one by one
for i,v in enumerate(A):
    print(i," ",v)

0   45
1   78
2   67
3   89
4   30
5   20


In [22]:
import numpy as np

In [23]:
#Create a numpy 1D array
A=np.array([45,67,89,23,10,76,43,45])
print(A)

[45 67 89 23 10 76 43 45]


In [24]:
#Access Data from 1D Numpy Array : -
#1. Through Indexing 
#Suppose access data at 2nd index means 3rd element
A[2]

89

In [25]:
#access data at 1st index and 4th index
A[[1,4]]

array([67, 10])

In [26]:
#OR
index=[1,4]
A[index]

array([67, 10])

In [27]:
'''
L=[34,67,89,32,14]
print(L)
print(type(L))
print(L[[1,4]])
'''

'\nL=[34,67,89,32,14]\nprint(L)\nprint(type(L))\nprint(L[[1,4]])\n'

In [28]:
#Through Slicing : - arrayname[start index:stop index:step]
#by default start index =0 if not given
#by default stop index : till end if not given
#by default step : +1 

In [29]:
#To access first 3 elements from 1D numpy array 
A[:3]

array([45, 67, 89])

In [30]:
A[-3:-1]

array([76, 43])

In [31]:
A[::-1] #to print seires in reverse order

array([45, 43, 76, 10, 23, 89, 67, 45])

In [32]:
#3. Conditional Filtering : for data access
#to access those record whose >60 , answer return True and
#false
print(A)
A[A>60]

[45 67 89 23 10 76 43 45]


array([67, 89, 76])

In [33]:
A[(A%2==0)|(A>=60)]

array([67, 89, 10, 76])

In [34]:
A

array([45, 67, 89, 23, 10, 76, 43, 45])

In [35]:
#replace all even no. with 0 and odd no. with 1
B=np.where(A%2==0,0,1)
print(B)

[1 1 1 1 0 0 1 1]


In [36]:
A

array([45, 67, 89, 23, 10, 76, 43, 45])

In [37]:
#Another way to create a numpy 1D array 
#use inbuilt method arange() : similar work as range() in
#python
#arange(start,stop,step)
X=np.arange(10,101,20)
print(X)

[10 30 50 70 90]


In [38]:
#zeros() ,ones(),empty()
Z=np.ones(20)
print(Z)
print(Z.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [39]:
import numpy as np

In [40]:
#Create a 2D numpy array 
A=np.array([[20,12,45,67],[30,87,40,29],[30,41,24,50],[32,87,64,87]])
print(A)

[[20 12 45 67]
 [30 87 40 29]
 [30 41 24 50]
 [32 87 64 87]]


In [41]:
#how many dimension
A.ndim

2

In [42]:
#How many no. of elements in given 2D array
A.size

16

In [43]:
A.dtype

dtype('int32')

In [44]:
A.itemsize

4

In [45]:
#how many bytes occupied by 2D numpy array A
A.nbytes #A.size*A.itemsize

64

In [46]:
#Access data from 2D numpy Array : -
#1. Through Indexing    2. Through Slicing  3. Conditional filtering
#1. Through Indexing : -
#Suppose retrieve value at 2nd rowindex and 3rd column index
A[2,3]

50

In [47]:
#to retrieve all details means all columns of 3rd student(2nd row index)
A[2,]

array([30, 41, 24, 50])

In [48]:
#Through Slicing
#retrieve all details of 1st row index and 2nd row index 
A[1:3,]

array([[30, 87, 40, 29],
       [30, 41, 24, 50]])

In [49]:
#to retrieve element of 1st to 2nd col index of all rows
A[:,1:3]

array([[12, 45],
       [87, 40],
       [41, 24],
       [87, 64]])

In [50]:
#to show last columns of all rows
A[:,-1]

array([67, 29, 50, 87])

In [51]:
A[A%2==0]

array([20, 12, 30, 40, 30, 24, 50, 32, 64])

In [52]:
print(A)

[[20 12 45 67]
 [30 87 40 29]
 [30 41 24 50]
 [32 87 64 87]]


In [53]:
#To sum of all elements of 2D array A 
A.sum() #np.sum(A) #20+12+45+67+30+87+40+........

745

In [54]:
#to find the sum of elements row wise (horizontally means axis=1)
#A.sum(axis=1)
#or
np.sum(A,axis=1)

array([144, 186, 145, 270])

In [55]:
#to find the sum of elements column wise (vertically means axis=0)
A.sum(axis=0)

array([112, 227, 173, 233])

In [56]:
print(A)

[[20 12 45 67]
 [30 87 40 29]
 [30 41 24 50]
 [32 87 64 87]]


In [57]:
X=np.sort(A,axis=0)[::-1] #descending order

In [58]:
X

array([[32, 87, 64, 87],
       [30, 87, 45, 67],
       [30, 41, 40, 50],
       [20, 12, 24, 29]])

In [59]:
A

array([[20, 12, 45, 67],
       [30, 87, 40, 29],
       [30, 41, 24, 50],
       [32, 87, 64, 87]])

In [60]:
#suppose we have 1D numpy array 
A=np.arange(10,81,10)
print(A)
print(A.size)
print(A.ndim)

[10 20 30 40 50 60 70 80]
8
1


In [61]:
#To change 1D numpy array to 2D numpy array
B=A.reshape(2,4)

In [62]:
A.ndim

1

In [63]:
B.ndim

2

In [64]:
print(B)

[[10 20 30 40]
 [50 60 70 80]]


In [65]:
#To converts 2D array into 1D array 
#1. ravel()  or 2.flatten()  or  3. reshape(-1)
B.ravel()

array([10, 20, 30, 40, 50, 60, 70, 80])

In [66]:
B.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80])

In [67]:
B.reshape(-1)

array([10, 20, 30, 40, 50, 60, 70, 80])

In [68]:
print(B)

[[10 20 30 40]
 [50 60 70 80]]


In [69]:
#transpose of matrix (means to converts row into column and column into row)
#use inbuilt method transpose
B.transpose()

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [70]:
B.T #transpose

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [71]:
#Sum of 2 matrix 
#create a 2 matrix X and Y
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])
print("First MAtrix : ")
print(X)
print("Second Matrix : ")
print(Y)

First MAtrix : 
[[1 2]
 [3 4]]
Second Matrix : 
[[5 6]
 [7 8]]


In [72]:
#sum of matrix 
X+Y

array([[ 6,  8],
       [10, 12]])

In [73]:
#subtract of matrix
X-Y

array([[-4, -4],
       [-4, -4]])

In [74]:
#cross multiplication
X*Y

array([[ 5, 12],
       [21, 32]])

In [75]:
#Dot multiplication or dot product
X.dot(Y)

array([[19, 22],
       [43, 50]])

In [76]:
print(X)

[[1 2]
 [3 4]]


In [77]:
print(Y)

[[5 6]
 [7 8]]


In [78]:
#to join 2 2D array , use inbuilt method concatenate()
#join horizontally means axis=1
Z=np.concatenate((X,Y),axis=1)
print(Z)

[[1 2 5 6]
 [3 4 7 8]]


In [79]:
np.concatenate((X,Y),axis=0) #vertically 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
import numpy as np

In [ ]:
#broadcasting 

In [81]:
#first create 2D numpy array
A=np.array([[5,6],[7,8]])
print(A)

[[5 6]
 [7 8]]


In [82]:
B=5 #scaler vector

In [83]:
A+B

array([[10, 11],
       [12, 13]])

In [84]:
A

array([[5, 6],
       [7, 8]])

In [85]:
B=np.array([[10,12]])
B.shape

(1, 2)

In [86]:
B

array([[10, 12]])

In [87]:
A+B   #[5   6] + [10  12]
#       7   8     10  12

array([[15, 18],
       [17, 20]])

In [ ]:
'''
[5   6] + [10 
7   8      12 ]
'''

In [88]:
A

array([[5, 6],
       [7, 8]])

In [90]:
B=np.array([[10],[12]])
B.shape

(2, 1)

In [91]:
B

array([[10],
       [12]])

In [92]:
A+B

array([[15, 16],
       [19, 20]])

In [93]:
#2D array : zeros()
Z=np.zeros((2,3)) #by default type float
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [94]:
Z=np.zeros((2,3),int)
print(Z)

[[0 0 0]
 [0 0 0]]


In [96]:
X=np.ones((3,3))
X.dtype

dtype('float64')

In [97]:
print(X)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [98]:
#Identity matrix 
I=np.identity(2) #unstood 2 by 2
I

array([[1., 0.],
       [0., 1.]])

In [100]:
I=np.identity(3,int) #no. of rows=3 and no. of cols=3
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [102]:
#another way to create a identity matrix  : eye()
I=np.eye(3,dtype='int')
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])