In [1]:
#third algorithm of classification :-
#SVM : Support vector machine : -
#There are 3 types of Kernal function of SVM
#1. Linear SVC  : use for linear data
#Non-Linear data
#2. polynomial kernal function : increase the low dimension to high dimension
#3. radial basis kernal function

#here 2. polynomial kernal function :
#increase the low dimension to high dimension
#3. radial basis kernal function  both are non-linear data



In [2]:
#SVM :  it is classification Supervised Machine Learning Algorithm .
#Support vector mactor , It is used to classify yes or no , 1 or 0 or
#multiclass classifier 
#means its classified categorical data 
#we use dataset mobile.csv

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
#to load dataset 
#df=pd.read_csv("mobile.csv")
df=pd.read_csv("bank.csv")
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [4]:
#Problem case study : - 
''' Basically company wants to launch their smart phone into the market ,
But they want to take a decision  whether they should keep the price more 
than 50000 or less than 50000 / - then It is the premium phone and it is less 
than 50000 than it is the normal phone .'''

#here target variable:  price_range  Whether the phone is premium means
#price_range>50000 or normal phone means price_range<50000 so that my target
#price_range=0 means <50000 and price_range=1 means >50000


' Basically company wants to launch their smart phone into the market ,\nBut they want to take a decision  whether they should keep the price more \nthan 50000 or less than 50000 / - then It is the premium phone and it is less \nthan 50000 than it is the normal phone .'

In [5]:
#check null values
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB


In [7]:
#separate X and Y means Input and output (Labelled means target)
X=df.drop("deposit",axis=1) #input features
Y=df["deposit"] #output means target which want to predict

In [8]:
#Train_Test_Split : 70% & 30%
from sklearn.model_selection import train_test_split

#Split our dataset in train test of 70% & 30%
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
#create object of StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train) #training data
X_test=ss.transform(X_test) #testing data

In [11]:
#create function 
def create_model(model):
    model.fit(X_train,Y_train)
    Y_pred=model.predict(X_test)
    print(classification_report(Y_test,Y_pred))
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [12]:
#Base Line Model : Take Logistic Regression 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [13]:
#Create the object of LogisticRegression class
lr=LogisticRegression ()

In [14]:
#call function
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

[[1441  319]
 [ 359 1230]]


In [15]:
#Support Vector machine : -
#Use SVM : support vector machine : this is a classification supervised learning
#algo.
'''There are various kernel functions :
1. Linear Kernel function (use linear separated data)
2. polynomial kernel function (non-linearly)
3. radial basis kernel function (non-linearly)'''

'There are various kernel functions :\n1. Linear Kernel function (use linear separated data)\n2. polynomial kernel function (non-linearly)\n3. radial basis kernel function (non-linearly)'

In [16]:
# Linear Kernel function means data is linearly separatable
#use inbuilt class LinearSVC which define in svm inbuilt package
from sklearn.svm import LinearSVC 
#Support vector classifier : SVC
#create the object of LinearSVC  class
svc=LinearSVC(random_state=1) #by default  hard margin means no add any error
#on training time

In [17]:
#call function 
svc=create_model(svc)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

[[1444  316]
 [ 364 1225]]


In [22]:
##score not bad but try its better 
#Apply soft margin means add externally error on training time
#create the object of inbuilt class LinearSVC  and passing parameter C
#for error
svc1=LinearSVC(random_state=1,C=0.08) #soft margin
#Range of C : 0.01 - 0.9
#soft margin means to reduced overfitting situation and remove outlier
#C is parameter which is used to add error on training time

In [23]:
#call function 
svc1=create_model(svc1)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.80      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

[[1446  314]
 [ 363 1226]]


In [ ]:
#Here if add external error on runtime but no changes in score means no 
#effect on score
#means we have data is non-linear data  , not linear dataset 
#So we will use polynomial kernel function means increase the dimension means
#to converts low dimension data into high dimension means if plot 1D then
#converting into 2D dimension and so on .

In [24]:
#2. polynomial Kernel function of SVM so, use inbuilt class SVC
from sklearn.svm import SVC 
#SVC inbuilt class for non-linear data

In [25]:
#create the object of SVC class
poly_svc=SVC(random_state=1,kernel="poly")

In [26]:
#call function 
poly_svc=create_model(poly_svc)

              precision    recall  f1-score   support

           0       0.82      0.81      0.81      1760
           1       0.79      0.80      0.80      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.81      0.80      0.80      3349

[[1417  343]
 [ 311 1278]]


In [27]:
#create the object of SVC class
r_svc=SVC(random_state=1,kernel="rbf")
#rbf means radial basis function


In [28]:
#call function 
r_svc=create_model(r_svc)

              precision    recall  f1-score   support

           0       0.84      0.80      0.82      1760
           1       0.79      0.84      0.81      1589

    accuracy                           0.82      3349
   macro avg       0.82      0.82      0.82      3349
weighted avg       0.82      0.82      0.82      3349

[[1407  353]
 [ 262 1327]]
